#!/usr/bin/env bash
# Provision Hetzner CX22 (Frankfurt) and write infra/staging/staging.env + ssh_config.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
STAGING_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
REPO_ROOT="$(cd "$STAGING_DIR/../.." && pwd)"

HCLOUD_TOKEN="${HCLOUD_TOKEN:-}"
HCLOUD_LOCATION="${HCLOUD_LOCATION:-fsn1}"
HCLOUD_SERVER_TYPE="${HCLOUD_SERVER_TYPE:-cx22}"
SERVER_NAME="${HALFAPP_SERVER_NAME:-halfapp-staging}"
HALFAPP_USER="${HALFAPP_USER:-halfapp}"
SSH_KEY_PATH="${HALFAPP_SSH_KEY:-$HOME/.ssh/halfapp_staging_ed25519}"
SSH_PUB_PATH="${SSH_KEY_PATH}.pub"

if [[ -z "$HCLOUD_TOKEN" ]]; then
  echo "Set HCLOUD_TOKEN (Hetzner Cloud API token) and re-run." >&2
  exit 1
fi
if [[ ! -f "$SSH_PUB_PATH" ]]; then
  echo "Missing SSH public key: $SSH_PUB_PATH" >&2
  echo "Generate: ssh-keygen -t ed25519 -f $SSH_KEY_PATH -C halfapp-staging" >&2
  exit 1
fi

api() {
  local method="$1" path="$2"
  shift 2
  curl -fsS -X "$method" -H "Authorization: Bearer $HCLOUD_TOKEN" -H "Content-Type: application/json" \
    "https://api.hetzner.cloud/v1$path" "$@"
}

PUB_KEY="$(cat "$SSH_PUB_PATH")"
KEY_NAME="halfapp-staging-$(echo "$PUB_KEY" | sha256sum | cut -c1-8)"

EXISTING_KEY_ID="$(api GET "/ssh_keys" | python3 -c "
import json,sys
name=sys.argv[1]
pub=open(sys.argv[2]).read().strip()
data=json.load(sys.stdin)
for k in data.get('ssh_keys',[]):
    if k.get('public_key','').strip()==pub:
        print(k['id']); raise SystemExit
for k in data.get('ssh_keys',[]):
    if k.get('name')==name:
        print(k['id']); raise SystemExit
" "$KEY_NAME" "$SSH_PUB_PATH" 2>/dev/null || true)"

if [[ -z "${EXISTING_KEY_ID:-}" ]]; then
  KEY_RESP="$(api POST "/ssh_keys" -d "{\"name\":\"$KEY_NAME\",\"public_key\":$(python3 -c "import json,sys; print(json.dumps(open(sys.argv[1]).read()))" "$SSH_PUB_PATH")}")"
  SSH_KEY_ID="$(echo "$KEY_RESP" | python3 -c "import json,sys; print(json.load(sys.stdin)['ssh_key']['id'])")"
else
  SSH_KEY_ID="$EXISTING_KEY_ID"
fi

CLOUD_INIT="$(sed "s|__HALFAPP_SSH_PUBLIC_KEY__|$PUB_KEY|g" "$STAGING_DIR/cloud-init.yaml")"
USER_DATA_B64="$(printf '%s' "$CLOUD_INIT" | base64 -w0 2>/dev/null || printf '%s' "$CLOUD_INIT" | base64)"

export SERVER_NAME HCLOUD_SERVER_TYPE HCLOUD_LOCATION SSH_KEY_ID USER_DATA_B64
CREATE_BODY="$(python3 - <<'PY'
import json, os
print(json.dumps({
  "name": os.environ["SERVER_NAME"],
  "server_type": os.environ["HCLOUD_SERVER_TYPE"],
  "location": os.environ["HCLOUD_LOCATION"],
  "image": "ubuntu-24.04",
  "ssh_keys": [int(os.environ["SSH_KEY_ID"])],
  "user_data": os.environ["USER_DATA_B64"],
  "labels": {"project": "halfapp", "env": "staging"},
}))
PY
)"

echo "Creating server $SERVER_NAME ($HCLOUD_SERVER_TYPE @ $HCLOUD_LOCATION)..."
CREATE_RESP="$(api POST "/servers" -d "$CREATE_BODY")"
SERVER_ID="$(echo "$CREATE_RESP" | python3 -c "import json,sys; print(json.load(sys.stdin)['server']['id'])")"
ROOT_PASS="$(echo "$CREATE_RESP" | python3 -c "import json,sys; d=json.load(sys.stdin); print(d.get('root_password') or '')")"

echo "Waiting for server $SERVER_ID to get an IPv4..."
for _ in $(seq 1 60); do
  SERVER_JSON="$(api GET "/servers/$SERVER_ID")"
  VPS_IP="$(echo "$SERVER_JSON" | python3 -c "import json,sys; s=json.load(sys.stdin)['server']; print(s.get('public_net',{}).get('ipv4',{}).get('ip') or '')")"
  STATUS="$(echo "$SERVER_JSON" | python3 -c "import json,sys; print(json.load(sys.stdin)['server']['status'])")"
  [[ -n "$VPS_IP" && "$VPS_IP" != "null" ]] && break
  sleep 5
done

if [[ -z "${VPS_IP:-}" ]]; then
  echo "Timed out waiting for IPv4." >&2
  exit 1
fi

VPS_HOST="$SERVER_NAME"
cat >"$STAGING_DIR/staging.env" <<EOF
# HalfApp staging VPS — generated by provision-hetzner.sh
VPS_HOST=$VPS_HOST
VPS_USER=$HALFAPP_USER
VPS_IP=$VPS_IP
HCLOUD_SERVER_ID=$SERVER_ID
HCLOUD_LOCATION=$HCLOUD_LOCATION
PROVISIONER=hetzner
PROVISIONED_AT=$(date -u +%Y-%m-%dT%H:%M:%SZ)
EOF

cat >"$STAGING_DIR/ssh_config" <<EOF
# Add to ~/.ssh/config (or include via: Include path/to/halfapp-driver/infra/staging/ssh_config)
Host staging halfapp-staging
    HostName $VPS_IP
    User $HALFAPP_USER
    IdentityFile $SSH_KEY_PATH
    IdentitiesOnly yes
    ServerAliveInterval 60
EOF

echo "$CREATE_RESP" >"$STAGING_DIR/.last-provision.json"
echo "Wrote $STAGING_DIR/staging.env and ssh_config"
echo "VPS_IP=$VPS_IP"
if [[ -n "$ROOT_PASS" ]]; then
  echo "Root password (one-time, discard after key login works): $ROOT_PASS"
fi
echo ""
echo "Wait ~2 min for cloud-init, then:"
echo "  ssh -i $SSH_KEY_PATH $HALFAPP_USER@$VPS_IP docker ps"
echo "  # or after merging ssh_config:"
echo "  ssh staging docker ps"
