# Provision Hetzner CX22 from Windows (PowerShell 5.1+).
# Usage: $env:HCLOUD_TOKEN = '...'; .\provision-hetzner.ps1
param(
    [string]$Location = $(if ($env:HCLOUD_LOCATION) { $env:HCLOUD_LOCATION } else { 'fsn1' }),
    [string]$ServerType = $(if ($env:HCLOUD_SERVER_TYPE) { $env:HCLOUD_SERVER_TYPE } else { 'cx22' }),
    [string]$ServerName = $(if ($env:HALFAPP_SERVER_NAME) { $env:HALFAPP_SERVER_NAME } else { 'halfapp-staging' }),
    [string]$SshKeyPath = $(if ($env:HALFAPP_SSH_KEY) { $env:HALFAPP_SSH_KEY } else { "$env:USERPROFILE\.ssh\halfapp_staging_ed25519" })
)

$ErrorActionPreference = 'Stop'
$StagingDir = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path

$token = $env:HCLOUD_TOKEN
if (-not $token) { throw 'Set HCLOUD_TOKEN (Hetzner Cloud API token).' }

$pubPath = "$SshKeyPath.pub"
if (-not (Test-Path $pubPath)) {
    throw "Missing SSH public key: $pubPath. Run: ssh-keygen -t ed25519 -f `"$SshKeyPath`" -C halfapp-staging"
}

function Invoke-HcloudApi {
    param([string]$Method, [string]$Path, [string]$Body = $null)
    $headers = @{ Authorization = "Bearer $token"; 'Content-Type' = 'application/json' }
    $uri = "https://api.hetzner.cloud/v1$Path"
    if ($Body) { return Invoke-RestMethod -Method $Method -Uri $uri -Headers $headers -Body $Body }
    return Invoke-RestMethod -Method $Method -Uri $uri -Headers $headers
}

$pubKey = (Get-Content $pubPath -Raw).Trim()
$keyHash = (Get-FileHash -Algorithm SHA256 -InputStream ([IO.MemoryStream]::new([Text.Encoding]::UTF8.GetBytes($pubKey)))).Hash.Substring(0, 8)
$keyName = "halfapp-staging-$keyHash"

$keys = (Invoke-HcloudApi GET '/ssh_keys').ssh_keys
$sshKeyId = ($keys | Where-Object { $_.public_key.Trim() -eq $pubKey } | Select-Object -First 1).id
if (-not $sshKeyId) {
    $sshKeyId = ($keys | Where-Object { $_.name -eq $keyName } | Select-Object -First 1).id
}
if (-not $sshKeyId) {
    $created = Invoke-HcloudApi POST '/ssh_keys' (@{ name = $keyName; public_key = $pubKey } | ConvertTo-Json)
    $sshKeyId = $created.ssh_key.id
}

$cloudInitTemplate = Get-Content (Join-Path $StagingDir 'cloud-init.yaml') -Raw
$cloudInit = $cloudInitTemplate.Replace('__HALFAPP_SSH_PUBLIC_KEY__', $pubKey)
$userDataB64 = [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes($cloudInit))

$createBody = @{
    name        = $ServerName
    server_type = $ServerType
    location    = $Location
    image       = 'ubuntu-24.04'
    ssh_keys    = @([int]$sshKeyId)
    user_data   = $userDataB64
    labels      = @{ project = 'halfapp'; env = 'staging' }
} | ConvertTo-Json -Depth 5

Write-Host "Creating $ServerName ($ServerType @ $Location)..."
$create = Invoke-HcloudApi POST '/servers' $createBody
$serverId = $create.server.id
$vpsIp = $null
for ($i = 0; $i -lt 60; $i++) {
    Start-Sleep -Seconds 5
    $srv = (Invoke-HcloudApi GET "/servers/$serverId").server
    $vpsIp = $srv.public_net.ipv4.ip
    if ($vpsIp) { break }
}
if (-not $vpsIp) { throw 'Timed out waiting for IPv4.' }

$halfappUser = 'halfapp'
$stagingEnv = @"
# HalfApp staging VPS — generated by provision-hetzner.ps1
VPS_HOST=$ServerName
VPS_USER=$halfappUser
VPS_IP=$vpsIp
HCLOUD_SERVER_ID=$serverId
HCLOUD_LOCATION=$Location
PROVISIONER=hetzner
PROVISIONED_AT=$((Get-Date).ToUniversalTime().ToString('yyyy-MM-ddTHH:mm:ssZ'))
"@
$stagingEnv | Set-Content -Encoding utf8 (Join-Path $StagingDir 'staging.env')

$sshConfig = @"
Host staging halfapp-staging
    HostName $vpsIp
    User $halfappUser
    IdentityFile $SshKeyPath
    IdentitiesOnly yes
    ServerAliveInterval 60
"@
$sshConfig | Set-Content -Encoding utf8 (Join-Path $StagingDir 'ssh_config')

$create | ConvertTo-Json -Depth 8 | Set-Content (Join-Path $StagingDir '.last-provision.json')
Write-Host "Wrote staging.env VPS_IP=$vpsIp"
Write-Host "After cloud-init (~2 min): ssh -i `"$SshKeyPath`" ${halfappUser}@${vpsIp} docker ps"
