#!/usr/bin/env bash
# Provision DigitalOcean droplet (~$6/mo) and write infra/staging/staging.env + ssh_config.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
STAGING_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

DIGITALOCEAN_ACCESS_TOKEN="${DIGITALOCEAN_ACCESS_TOKEN:-}"
DO_REGION="${DO_REGION:-nyc3}"
DO_SIZE="${DO_SIZE:-s-1vcpu-1gb}"
SERVER_NAME="${HALFAPP_SERVER_NAME:-halfapp-staging}"
HALFAPP_USER="${HALFAPP_USER:-halfapp}"
SSH_KEY_PATH="${HALFAPP_SSH_KEY:-$HOME/.ssh/halfapp_staging_ed25519}"
SSH_PUB_PATH="${SSH_KEY_PATH}.pub"

if [[ -z "$DIGITALOCEAN_ACCESS_TOKEN" ]]; then
  echo "Set DIGITALOCEAN_ACCESS_TOKEN and re-run." >&2
  exit 1
fi
if [[ ! -f "$SSH_PUB_PATH" ]]; then
  echo "Missing SSH public key: $SSH_PUB_PATH" >&2
  exit 1
fi

do_api() {
  curl -fsS -X "$1" -H "Authorization: Bearer $DIGITALOCEAN_ACCESS_TOKEN" -H "Content-Type: application/json" \
    "https://api.digitalocean.com/v2$2" "${@:3}"
}

PUB_KEY="$(cat "$SSH_PUB_PATH")"
KEY_NAME="halfapp-staging"

KEY_ID="$(do_api GET "/account/keys" | python3 -c "
import json,sys
pub=open('$SSH_PUB_PATH').read().strip()
data=json.load(sys.stdin)
for k in data.get('ssh_keys',[]):
    if k.get('public_key','').strip()==pub:
        print(k['id']); raise SystemExit(0)
" 2>/dev/null || true)"

if [[ -z "${KEY_ID:-}" ]]; then
  KEY_ID="$(do_api POST "/account/keys" -d "{\"name\":\"$KEY_NAME\",\"public_key\":$(python3 -c "import json; print(json.dumps(open('$SSH_PUB_PATH').read()))")}" \
    | python3 -c "import json,sys; print(json.load(sys.stdin)['ssh_key']['id'])")"
fi

export CLOUD_INIT_FILE="$STAGING_DIR/cloud-init.yaml" SSH_PUB_PATH="$SSH_PUB_PATH" SERVER_NAME DO_REGION DO_SIZE KEY_ID="$KEY_ID"
CREATE_BODY="$(python3 - <<PY
import json, os, base64
cloud = open(os.environ["CLOUD_INIT_FILE"]).read().replace("__HALFAPP_SSH_PUBLIC_KEY__", open(os.environ["SSH_PUB_PATH"]).read().strip())
print(json.dumps({
  "name": os.environ["SERVER_NAME"],
  "region": os.environ["DO_REGION"],
  "size": os.environ["DO_SIZE"],
  "image": "ubuntu-24-04-x64",
  "ssh_keys": [int(os.environ["KEY_ID"])],
  "user_data": base64.b64encode(cloud.encode()).decode(),
  "tags": ["halfapp", "staging"],
}))
PY
)"
CREATE_RESP="$(do_api POST "/droplets" -d "$CREATE_BODY")"

DROPLET_ID="$(echo "$CREATE_RESP" | python3 -c "import json,sys; print(json.load(sys.stdin)['droplet']['id'])")"

echo "Waiting for droplet $DROPLET_ID..."
for _ in $(seq 1 60); do
  DROPLET_JSON="$(do_api GET "/droplets/$DROPLET_ID")"
  VPS_IP="$(echo "$DROPLET_JSON" | python3 -c "
import json,sys
d=json.load(sys.stdin)['droplet']
for n in d.get('networks',{}).get('v4',[]):
    if n.get('type')=='public':
        print(n['ip_address']); break
")"
  [[ -n "$VPS_IP" ]] && break
  sleep 5
done

[[ -n "${VPS_IP:-}" ]] || { echo "No public IP." >&2; exit 1; }

cat >"$STAGING_DIR/staging.env" <<EOF
# HalfApp staging VPS — generated by provision-digitalocean.sh
VPS_HOST=$SERVER_NAME
VPS_USER=$HALFAPP_USER
VPS_IP=$VPS_IP
DO_DROPLET_ID=$DROPLET_ID
DO_REGION=$DO_REGION
PROVISIONER=digitalocean
PROVISIONED_AT=$(date -u +%Y-%m-%dT%H:%M:%SZ)
EOF

cat >"$STAGING_DIR/ssh_config" <<EOF
Host staging halfapp-staging
    HostName $VPS_IP
    User $HALFAPP_USER
    IdentityFile $SSH_KEY_PATH
    IdentitiesOnly yes
    ServerAliveInterval 60
EOF

echo "Wrote staging.env (VPS_IP=$VPS_IP) and ssh_config"
